---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Create an e-mail subscription to an SNS topic, because Terraform won't do it.
Parameters:
  TopicArn:
    Type: String
    Description: >
      ARN for the SNS topic to subscribe to
  EMailAddress:
    Type: String
    Description: >
      E-mail address to add to the subscription
  Protocol:
    Type: String
    Description: >
      Whether to encode the e-mail body in JSON or not
    AllowedValues:
      - email
      - email-json
    Default: email
Resources:
  RDSSub:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !Ref EMailAddress
      Protocol: !Ref Protocol
      TopicArn: !Ref TopicArn
