  process:
    name: s3-event-reader-${opt:stage, self:provider.stage}
    handler: src/handlers/${self:provider.name}/process-s3EventReader-handler.handle
    role: arn:aws:iam::820643439592:role/LambdaS3Execute
    timeout: 300
    package:
      include:
        - src/handlers/${self:provider.name}/process-s3EventReader-handler.js
        - node_modules/s3EventReader-process/**
    events:
     - s3:
          bucket: tvx-middleware-nonprod
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
      # - http:
      #     path: process
      #     method: post
      #     cors: true
